server:
  port : 8082

rabbitmq:
  request:
    host: localhost
    port: 5672
    username: guest
    password: guest
    exchenge:
      producer: ex.producer.news
    routing-key:
      producer: rk.producer.news
    deadletter:
      producer: dl.producer.news

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/news?useTimezone=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

